### ISSUE TITLE
recon.runner.train

### ISSUE THREAD

**Issue by superlittl** [Karbo123/RGBD-Diffusion#2]
Hi Jiabao,
I have a question regarding your code, and I was wondering if you could provide the `recon.runner.train` module mentioned in your documentation and command line examples. It seems to contain the training logic, and having access to this module would greatly help me in understanding and using your code effectively.
If it's possible to share the module or point me to its location, I would greatly appreciate it. Thank you for your hard work and contributions!

**Comment by Karbo123** [comment]
don't download the code in zip, and make sure you have run this line: 
```
git submodule update --init --recursive
```

the recon module is in   https://github.com/Karbo123/recon/blob/master/recon/runner/train.py
