### ISSUE TITLE
[Error solved] Error while loading config with gorilla (@from diffusers import DDIMScheduler)

### ISSUE THREAD

**Issue by robot0321** [Karbo123/RGBD-Diffusion#3]
Hi, Thank you for your interesting work. 
I just want to write an issue to reduce the burden on other users of debugging.

I've tried to run your code, but I got an error when loading the config file with Gorilla.
I commented out each block and I finally found that this code makes an error.
(Note that the original error report is confusing.) 
~~~python
from diffusers import DDIMScheduler
~~~
~~~
ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/home/chung/anaconda3/lib/python3.9/site-packages/urllib3/util/ssl_.py)
~~~

When I was googling, someone said that `botocore does not support urllib3 2.0 yet`.
So I re-install urllib3 with the latest version under 2.0, which is
~~~
pip install urllib3==1.26.16
~~~

and it solved!
By the way, I want to thank to authors for the nice work again! :)

**Comment by Karbo123** [comment]
Thanks for putting the solution here, it looks like it was caused by a third party library, gorilla, I am glad you finally worked it out.
